name: Check Markdown
on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-quiet-mode: 'yes'
      - name: Check format
        # Please, make sure to enable Markdown linting in your IDE. For the Visual Studio Code editor it is
        # `davidanson.vscode-markdownlint` that is already specified in the `.vscode/extensions.json` file.
        run: |
          files=$(git diff --diff-filter=ACMRT --name-only origin/${{ github.event.repository.default_branch }}.. "*.md")
          if [ -n "$files" ]; then
            docker run --rm \
              -v $PWD:/workdir \
              ghcr.io/igorshubovych/markdownlint-cli:latest \
                $files \
                --disable MD013
          fi
